[WIP] add new flink job to update governance data quality
aureliusenterprise/aurelius pull request #19
Opened 2024-12-02 14:44 UTC by lorandvatamany

- [ ] Check if all quality rules were mapped
- [ ] update post install steps

2024-12-05 07:55 UTC, thijsfranck-fugro requested changes

2024-12-05 07:55 UTC, thijsfranck-fugro commented on libs/m4i-data-management/.gitignore
why do we need a separate .gitignore file for this library?

2024-12-05 07:55 UTC, thijsfranck-fugro commented on libs/m4i-data-management/README.md
> +## Installation
These instructions are no longer correct in the context of this repository. Let's update them or remove them.

2024-12-05 07:55 UTC, thijsfranck-fugro commented on libs/m4i-data-management/pyproject.toml
> +    dict_hash = "~1.3"
Can you please make sure that all external dependencies used by this library are listed here? For example I saw pandas being imported in some of the modules.

2024-12-05 07:55 UTC, thijsfranck-fugro commented on libs/m4i-governance-data-quality/.gitignore
Same question as for the other project - do we need a separate gitignore for this library and if so why?

2024-12-05 07:55 UTC, thijsfranck-fugro commented on libs/m4i-governance-data-quality/README.md
Can you please update this readme? For example, I still see old library names referenced 😂

2025-01-07 14:17 UTC, thijsfranck-fugro approved these changes

2025-01-07 14:18 UTC, thijs-franck approved these changes

2025-01-07 14:37 UTC, merged